name: app03
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 国际化
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  # 网络请求
  dio: ^3.0.9
  dio_cookie_manager: ^1.0.0
  path_provider: ^1.6.11
  # 日期
  date_format: ^1.0.8
  flutter_cupertino_date_picker: ^1.0.26+2
  # 国际化
  # flutter_cupertino_localizations: ^1.0.1
  # 轮播图
  flutter_swiper: ^1.1.6
  # toast
  fluttertoast: ^4.0.1
  # 下拉刷新 上拉分页加载更多
  pull_to_refresh: ^1.6.0
  # loading
  flutter_spinkit: "^4.1.2"
  # dva
  # dva_flutter: ^0.1.2
  # dva_dart: ^0.1.2
  # Redux
  flutter_redux: ^0.6.0
  redux: ^4.0.0
  # 加载html 字符串
  flutter_html: ^1.0.0
  # webview
  flutter_inappwebview: ^4.0.0+4
  # webview 第二个插件
  # flutter_webview_plugin: ^0.3.11
  # 设备信息
  device_info: ^0.4.2+4
  # 高德定位
  amap_location: ^0.2.0
  # 权限
  # simple_permissions: ^0.1.9
  # 拍照和相册
  image_picker: ^0.6.7+4
  # 状态管理
  provider: ^4.3.1
  # 视频播放
  video_player: ^0.10.11+2
  chewie: ^0.9.10
  # 监听网络变化
  connectivity: ^0.4.9
  # 本地存储
  shared_preferences: ^0.5.8
  # 扫描二维码和条形码
  barcode_scan: ^3.0.1
  # 自动升级涉及到的库
  # 检测版本号
  package_info: ^0.4.1
  # 获取文件存储路径
  # path_provider: ^1.6.11 # 上面已经下载了
  # 下载文件
  flutter_downloader: ^1.4.4
  # 打开文件插件
  open_file: ^3.0.1
  # 自动升级涉及到的库 end
  # 打开外部浏览器、打开外部应用、拨打电话、发送短信
  url_launcher: ^5.5.0
  # 直播（视频播放）
  flutter_ijkplayer: ^0.3.5+1
  # 生物识别 指纹或者人脸识别
  local_auth: ^0.6.2+3


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/a.jpeg
    - images/2.0x/a.jpeg
    - images/3.0x/a.jpeg
    - images/4.0x/a.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
